title: FigmaToCode：设计师转前端开发者
description: 专为设计师设计的前端技能提升计划，在AI工具协助下高效掌握现代前端技术栈
baseurl: "/FigmaToCode"
url: "https://kklauden.github.io"

# GitHub Pages settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Header pages for navigation
header_pages:
  - modules/index.md
  - devlog/index.md
  - news/index.md

# Author
author:
  name: FigmaToCode Learning
  email: figmatocode@example.com

# SEO
lang: zh-CN
timezone: Asia/Shanghai

# Markdown processing
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Collections
collections:
  modules:
    output: true
    permalink: /modules/:name/

# Include non-standard directories
include:
  - modules
  - devlog
  - news

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "FigmaToCode Learning"
  - scope:
      path: ""
      type: "modules"
    values:
      layout: "module"
  - scope:
      path: ""
      type: "podcasts"
    values:
      layout: "podcast"

# Exclude from processing
exclude:
  - .git/
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/